import type { TableView } from '../game/model';
import type { DemoSession } from '../game/demo';
import { cardMarkup } from './cards';
export function hudMarkup(view:TableView,session?:DemoSession):string {
 const finished=session?.kind==='finished';
 const history=session?.history??['Fly bets 4.25 BB.'];
 return `<div class="casino-app"><header class="site-header"><a class="brand" href="/" aria-label="Poker vs. a Fruit Fly">fly<span class="brand-italic">poker</span></a><div class="header-right"><button class="btn btn-ghost" data-info>About</button><button class="btn" data-new-game>New hand</button></div></header>
 <main><section aria-label="Casino poker table"><div class="casino-stage"><div class="scene" data-scene data-phase="${view.phase}" aria-label="Casino table with a fly sitting directly across from you"></div><div class="vignette"></div>
 <div class="seat fly-seat"><span>Fly</span><strong>${view.flyStackBb} <small>BB</small></strong></div>
 <div class="opponent-cards" aria-label="${finished&&view.phase==='showdown'?'Revealed fly hand':'Opponent has two hidden cards'}">${finished&&view.phase==='showdown'?cardMarkup('AH')+cardMarkup('8S'):'<span class="card-back"></span><span class="card-back"></span>'}</div>
 <div class="community"><div class="pot-chip"><span>Pot</span><strong>${view.potBb} <small>BB</small></strong></div><div class="board" aria-label="Community cards">${view.board.map(cardMarkup).join('')}${Array.from({length:5-view.board.length},()=>'<span class="empty-card"></span>').join('')}</div><span class="street-label">Hand ${view.handNumber} · ${view.board.length===3?'Flop':view.board.length===4?'Turn':'River'}</span></div>
 <div class="your-hand" aria-label="Your hole cards">${view.playerCards.map(cardMarkup).join('')}</div><div class="seat player-seat"><span>You</span><strong>${view.playerStackBb} <small>BB</small></strong></div></div>
 <div class="action-dock" data-controls><div class="turn-message" role="status">${session?.message??'The fly bets 4.25 BB. Your move.'}</div><nav class="action-controls" aria-label="Poker actions"><button class="btn fold" data-action="fold" ${finished?'disabled':''}>Fold <kbd>F</kbd></button><button class="btn call" data-action="call" ${finished?'disabled':''}>${session?.toCall===0?'Check':'Call 4.25 BB'} <kbd>C</kbd></button><div class="raise-control"><label for="raise-amount">${session?.toCall===0?'Bet':'Raise to'} <output data-raise-value>8.5 BB</output></label><input id="raise-amount" data-raise-slider type="range" min="${Math.min(view.playerStackBb,session?.toCall?session.toCall*2:1)}" max="${view.playerStackBb}" step=".25" value="8.5" ${finished?'disabled':''}/></div><button class="btn btn-primary" data-action="raise" ${finished?'disabled':''}>${session?.toCall===0?'Bet':'Raise'} <span data-raise-button>8.5 BB</span> <kbd>R</kbd></button></nav></div></section>
 <details class="hand-log"><summary>Hand history <span>＋</span></summary><ol>${history.slice(-6).map(entry=>`<li>${entry}</li>`).join('')}</ol></details></main>
 <dialog data-about><button class="dialog-close btn" data-close aria-label="Close information">×</button><h2>Poker against a fly.</h2><p>A local, scripted heads-up demo. Call, check, bet, or fold. Keyboard controls are F, C, and R. New hand resets the table.</p><p>The connectome backend is not connected to this view. This hand uses a fixed deck and scripted responses. No money is involved.</p><p>Chip colors show denominations in big blinds. Black is 25 BB, green is 5 BB, blue is 1 BB, and white is 0.25 BB. The stack and pot labels give exact amounts.</p><p>Design inspired by <a href="https://github.com/cesp99/fly-chess">flychess</a>. Cards by <a href="https://www.me.uk/cards/">Adrian Kennard</a>, CC0. Fly artwork <a href="/assets/fly-chess-LICENSE.txt">MIT license</a>.</p><button class="btn btn-primary" data-close>Back to table</button></dialog></div>`;
}
