import { legalActions } from '../game/poker';
import { bb,type PokerState } from '../game/pokerTypes';
import { cardMarkup } from './cards';
import type {BrainStatus} from '../brain/protocol';
import type { Presentation } from './pokerView';
export function pokerMarkup(state:PokerState,display:Presentation,brain:BrainStatus={kind:'loading'},runtime={inferences:0,inferenceMs:0}):string{
 const escape=(text:string)=>text.replace(/[&<>"]/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[character]??character));
 const brainLabel=brain.kind==='ready'?'Neural fly · local':brain.kind==='loading'?'Loading brain…':'Brain unavailable';
 const metadata=brain.kind==='ready'?brain.metadata:undefined;
 const view=display.table;const legal=legalActions(state);const playerTurn=state.kind==='betting'&&state.turn==='player'&&!display.busy;
 const finished=state.kind==='complete';const matchOver=finished&&(!state.stacks.player||!state.stacks.fly);
 const disabled=(allowed:boolean)=>playerTurn&&allowed?'':'disabled';
 const cards=(hand:readonly typeof view.board[number][])=>hand.map(card=>`<span class="card-slot ${display.winningCards.includes(card)?'winning-card':''} ${display.dealingCards.includes(card)?'deal-card':''}" style="--deal-delay:${Math.max(0,display.dealingCards.indexOf(card))*80}ms">${cardMarkup(card)}</span>`).join('');
 const raise=legal.raise.kind==='raise'?legal.raise:{minTo:0,maxTo:0};
 return `<div class="casino-app"><header class="site-header"><a class="brand" href="/" aria-label="Poker vs. a Fruit Fly">fly<span class="brand-italic">poker</span></a><div class="header-right"><button class="btn btn-ghost" data-info>About</button><button class="btn" data-reset>Restart match</button></div></header>
 <div class="brain-status" role="status" data-brain-state="${brain.kind}" data-brain-model-hash="${metadata?.modelHash??''}" data-brain-inferences="${runtime.inferences}" data-brain-ms="${runtime.inferenceMs.toFixed(1)}">${brainLabel}${brain.kind==='error'?'<button class="btn" data-brain-retry>Retry brain</button>':''}</div>
 <main><section aria-label="Casino poker table"><div class="casino-stage"><div class="scene" data-scene data-phase="${view.phase}" aria-label="Poker casino with a fly seated across from you"></div><div class="vignette"></div>
 <div class="seat fly-seat ${display.winner==='fly'||display.winner==='split'?'winner-seat':''} ${display.animation==='win'&&(display.winner==='fly'||display.winner==='split')?'win-animation':''}"><span>Fly ${state.dealer==='fly'?'<span class="button-mark" title="Dealer button">D</span>':''}</span><strong>${view.flyStackBb} <small>BB</small></strong></div>
 <div class="opponent-cards ${display.opponentCards.length?'revealed-hand':''} ${display.animation==='reveal'?'reveal-animation':''}" aria-label="${display.opponentCards.length?'Revealed fly hand':'Two hidden fly cards'}">${display.opponentCards.length?cards(display.opponentCards):'<span class="card-back"></span><span class="card-back"></span>'}</div>
 <div class="community"><div class="pot-chip"><span>Pot</span><strong>${view.potBb} <small>BB</small></strong></div><div class="board" aria-label="Community cards">${cards(view.board)}${Array.from({length:5-view.board.length},()=>'<span class="empty-card"></span>').join('')}</div><span class="street-label">Hand ${state.handNumber} Â· ${view.board.length===0?'Preflop':view.board.length===3?'Flop':view.board.length===4?'Turn':'River'} Â· Blinds 0.5 / 1 BB</span></div>
 <div class="your-hand" aria-label="Your hole cards">${cards(view.playerCards)}</div><div class="seat player-seat ${display.winner==='player'||display.winner==='split'?'winner-seat':''} ${display.animation==='win'&&(display.winner==='player'||display.winner==='split')?'win-animation':''}"><span>You ${state.dealer==='player'?'<span class="button-mark" title="Dealer button">D</span>':''}</span><strong>${view.playerStackBb} <small>BB</small></strong></div></div>
 <div class="action-dock" data-controls aria-busy="${display.busy}"><div class="turn-message" role="status">${display.message}</div><nav class="action-controls" aria-label="Poker actions">${finished&&!display.busy?`<button class="btn btn-primary next-hand" data-next>${matchOver?'Rematch Â· 100 BB each':'Deal next hand'}</button>`:`<button class="btn fold" data-action="fold" ${disabled(legal.canFold)}>Fold <kbd>F</kbd></button><button class="btn call" data-action="call" ${disabled(legal.canCheck||legal.call>0)}>${legal.canCheck?'Check':`Call ${bb(legal.call)} BB`} <kbd>C</kbd></button><div class="raise-control"><label for="raise-amount">${state.kind==='betting'&&state.currentBet?'Raise to':'Bet'} <output data-raise-value>${bb(raise.minTo)} BB</output></label><input id="raise-amount" data-raise-slider type="range" min="${raise.minTo}" max="${raise.maxTo}" step="1" value="${raise.minTo}" ${disabled(legal.raise.kind==='raise')}/></div><button class="btn btn-primary" data-action="raise" ${disabled(legal.raise.kind==='raise')}>${state.kind==='betting'&&state.currentBet?'Raise to':'Bet'} <span data-raise-button>${bb(raise.minTo)} BB</span> <kbd>R</kbd></button><button class="btn all-in" data-action="all-in" ${disabled(legal.canAllIn)}>All-in <kbd>A</kbd></button>`}</nav></div></section>
 <details class="hand-log"><summary>Hand history <span>ï¼‹</span></summary><ol>${state.history.map(entry=>`<li>${entry}</li>`).join('')}</ol></details></main>
 <dialog data-about><button class="dialog-close btn" data-close aria-label="Close information">Ã—</button><h2>Poker against a fly.</h2><p>Heads-up no-limit Texas Holdâ€™em. Each player buys in for 100 BB. Blinds are 0.5 / 1 BB. Play through preflop, flop, turn, and river. Best five of seven cards wins; ties split the pot.</p><p>The button alternates after every hand. Your chips carry forward until one player wins the match. Restart match or Rematch resets both stacks. F folds, C checks or calls, R bets or raises, and A goes all-in.</p><p>The fly uses a locally running recurrent neural model on 134,209 neurons and 2,700,513 connections from a FlyWire-derived connectome. Training learns connection magnitudes, neuron leaks, sensory projection and motor policy/value heads while preserving wiring and synaptic signs. It is a rate approximation, not a living brain or a spiking simulation. The model sees only its own cards, public board, stacks and legal bets. Eight sparse steps produce a masked poker action in a browser Worker; no turn data is sent to a server. The policy chooses its highest legal logit. No heuristic bot is used.</p><p>${brain.kind==='ready'?`Loaded seed ${brain.metadata.seed} · ${brain.metadata.warmSteps} imitation updates · ${brain.metadata.updates} actor-critic updates. Model SHA-256 <code>${brain.metadata.modelHash}</code>. ${runtime.inferences} local decisions; last inference ${runtime.inferenceMs.toFixed(1)} ms.`:brain.kind==='error'?`Model stopped: ${escape(brain.message)}`:'Downloading and verifying the trained model…'}</p><p>Poker training uses sampled hidden-card equity imitation and on-policy self-play against a mixture of opponents. This pilot has not established strong or optimal play. Graph data is CC BY-NC 4.0. No money is involved.</p><p>Chip denominations are 25 BB in black, 5 BB in green, 1 BB in blue, and 0.25 BB in white. Labels show exact amounts. Cards by <a href="https://www.me.uk/cards/">Adrian Kennard</a>, CC0. Design inspired by <a href="https://github.com/cesp99/fly-chess">flychess</a>.</p><button class="btn btn-primary" data-close>Back to table</button></dialog></div>`;
}

