import { legalActions } from '../game/poker';
import { bb,type PokerState } from '../game/pokerTypes';
import { cardMarkup } from './cards';
import type { Presentation } from './pokerView';
export function pokerMarkup(state:PokerState,display:Presentation):string{
 const view=display.table;const legal=legalActions(state);const playerTurn=state.kind==='betting'&&state.turn==='player'&&!display.busy;
 const finished=state.kind==='complete';const matchOver=finished&&(!state.stacks.player||!state.stacks.fly);
 const disabled=(allowed:boolean)=>playerTurn&&allowed?'':'disabled';
 const cards=(hand:readonly typeof view.board[number][])=>hand.map(card=>`<span class="card-slot ${display.winningCards.includes(card)?'winning-card':''}">${cardMarkup(card)}</span>`).join('');
 const raise=legal.raise.kind==='raise'?legal.raise:{minTo:0,maxTo:0};
 return `<div class="casino-app"><header class="site-header"><a class="brand" href="/" aria-label="Poker vs. a Fruit Fly">fly<span class="brand-italic">poker</span></a><div class="header-right"><button class="btn btn-ghost" data-info>About</button><button class="btn" data-reset>Restart match</button></div></header>
 <main><section aria-label="Casino poker table"><div class="casino-stage"><div class="scene" data-scene data-phase="${view.phase}" aria-label="Poker casino with a fly seated across from you"></div><div class="vignette"></div>
 <div class="seat fly-seat ${display.winner==='fly'||display.winner==='split'?'winner-seat':''}"><span>Fly ${state.dealer==='fly'?'<span class="button-mark" title="Dealer button">D</span>':''}</span><strong>${view.flyStackBb} <small>BB</small></strong></div>
 <div class="opponent-cards ${display.opponentCards.length?'revealed-hand':''}" aria-label="${display.opponentCards.length?'Revealed fly hand':'Two hidden fly cards'}">${display.opponentCards.length?cards(display.opponentCards):'<span class="card-back"></span><span class="card-back"></span>'}</div>
 <div class="community"><div class="pot-chip"><span>Pot</span><strong>${view.potBb} <small>BB</small></strong></div><div class="board" aria-label="Community cards">${cards(view.board)}${Array.from({length:5-view.board.length},()=>'<span class="empty-card"></span>').join('')}</div><span class="street-label">Hand ${state.handNumber} · ${view.board.length===0?'Preflop':view.board.length===3?'Flop':view.board.length===4?'Turn':'River'} · Blinds 0.5 / 1 BB</span></div>
 <div class="your-hand" aria-label="Your hole cards">${cards(view.playerCards)}</div><div class="seat player-seat ${display.winner==='player'||display.winner==='split'?'winner-seat':''}"><span>You ${state.dealer==='player'?'<span class="button-mark" title="Dealer button">D</span>':''}</span><strong>${view.playerStackBb} <small>BB</small></strong></div></div>
 <div class="action-dock" data-controls aria-busy="${display.busy}"><div class="turn-message" role="status">${display.message}</div><nav class="action-controls" aria-label="Poker actions">${finished&&!display.busy?`<button class="btn btn-primary next-hand" data-next>${matchOver?'Rematch · 100 BB each':'Deal next hand'}</button>`:`<button class="btn fold" data-action="fold" ${disabled(legal.canFold)}>Fold <kbd>F</kbd></button><button class="btn call" data-action="call" ${disabled(legal.canCheck||legal.call>0)}>${legal.canCheck?'Check':`Call ${bb(legal.call)} BB`} <kbd>C</kbd></button><div class="raise-control"><label for="raise-amount">${state.kind==='betting'&&state.currentBet?'Raise to':'Bet'} <output data-raise-value>${bb(raise.minTo)} BB</output></label><input id="raise-amount" data-raise-slider type="range" min="${raise.minTo}" max="${raise.maxTo}" step="1" value="${raise.minTo}" ${disabled(legal.raise.kind==='raise')}/></div><button class="btn btn-primary" data-action="raise" ${disabled(legal.raise.kind==='raise')}>${state.kind==='betting'&&state.currentBet?'Raise to':'Bet'} <span data-raise-button>${bb(raise.minTo)} BB</span> <kbd>R</kbd></button><button class="btn all-in" data-action="all-in" ${disabled(legal.canAllIn)}>All-in <kbd>A</kbd></button>`}</nav></div></section>
 <details class="hand-log"><summary>Hand history <span>＋</span></summary><ol>${state.history.map(entry=>`<li>${entry}</li>`).join('')}</ol></details></main>
 <dialog data-about><button class="dialog-close btn" data-close aria-label="Close information">×</button><h2>Poker against a fly.</h2><p>Heads-up no-limit Texas Hold’em. Each player buys in for 100 BB. Blinds are 0.5 / 1 BB. Play through preflop, flop, turn, and river. Best five of seven cards wins; ties split the pot.</p><p>The button alternates after every hand. Your chips carry forward until one player wins the match. Restart match or Rematch resets both stacks. F folds, C checks or calls, R bets or raises, and A goes all-in.</p><p>The fly is a local poker bot. It sees its own cards and the public board, with randomized decisions. The neural backend is not connected. No money is involved.</p><p>Chip denominations are 25 BB in black, 5 BB in green, 1 BB in blue, and 0.25 BB in white. Labels show exact amounts. Cards by <a href="https://www.me.uk/cards/">Adrian Kennard</a>, CC0. Design inspired by <a href="https://github.com/cesp99/fly-chess">flychess</a>.</p><button class="btn btn-primary" data-close>Back to table</button></dialog></div>`;
}

